USE [master]
GO
/****** Object:  Database [GreatPizza]    Script Date: 5/10/2020 5:43:46 PM ******/
CREATE DATABASE [GreatPizza]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GreatPizza', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\GreatPizza.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'GreatPizza_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\GreatPizza_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [GreatPizza] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GreatPizza].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [GreatPizza] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [GreatPizza] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [GreatPizza] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [GreatPizza] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [GreatPizza] SET ARITHABORT OFF 
GO
ALTER DATABASE [GreatPizza] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [GreatPizza] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [GreatPizza] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [GreatPizza] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [GreatPizza] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [GreatPizza] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [GreatPizza] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [GreatPizza] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [GreatPizza] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [GreatPizza] SET  DISABLE_BROKER 
GO
ALTER DATABASE [GreatPizza] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [GreatPizza] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [GreatPizza] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [GreatPizza] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [GreatPizza] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [GreatPizza] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [GreatPizza] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [GreatPizza] SET RECOVERY FULL 
GO
ALTER DATABASE [GreatPizza] SET  MULTI_USER 
GO
ALTER DATABASE [GreatPizza] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [GreatPizza] SET DB_CHAINING OFF 
GO
ALTER DATABASE [GreatPizza] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [GreatPizza] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [GreatPizza] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'GreatPizza', N'ON'
GO
ALTER DATABASE [GreatPizza] SET QUERY_STORE = OFF
GO
USE [GreatPizza]
GO
/****** Object:  Table [dbo].[Pizza]    Script Date: 5/10/2020 5:43:46 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Pizza](
	[Name] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Pizza] PRIMARY KEY CLUSTERED 
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PizzaTopping]    Script Date: 5/10/2020 5:43:46 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PizzaTopping](
	[PizzaName] [varchar](50) NOT NULL,
	[ToppingName] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Pizza_Topping] PRIMARY KEY CLUSTERED 
(
	[PizzaName] ASC,
	[ToppingName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Topping]    Script Date: 5/10/2020 5:43:46 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Topping](
	[Name] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Topping] PRIMARY KEY CLUSTERED 
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PizzaTopping]  WITH CHECK ADD  CONSTRAINT [FK_Pizza] FOREIGN KEY([PizzaName])
REFERENCES [dbo].[Pizza] ([Name])
GO
ALTER TABLE [dbo].[PizzaTopping] CHECK CONSTRAINT [FK_Pizza]
GO
ALTER TABLE [dbo].[PizzaTopping]  WITH CHECK ADD  CONSTRAINT [FK_Topping] FOREIGN KEY([ToppingName])
REFERENCES [dbo].[Topping] ([Name])
GO
ALTER TABLE [dbo].[PizzaTopping] CHECK CONSTRAINT [FK_Topping]
GO
USE [master]
GO
ALTER DATABASE [GreatPizza] SET  READ_WRITE 
GO
